import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { ConvexClientProvider } from "@/provider";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { Fira_Code, Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const fira_code = Fira_Code({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${fira_code.variable} ${GeistSans.variable}  bg-background antialiased`}
      >
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
